apiVersion: v1
data:
  DATABASE_URL: cG9zdGdyZXNxbDovL2RiYWRtaW46V0VRR2NfMm1weVRYRXBDUGthNmUyMXJsRFh3cFA2UlJfaHcwZVdrTDl4c0A0LjE1Mi4yMDEuMTcxOjU0MzIvb2ZmY2FsbF9haQ==
  JWT_SECRET: SzkrUjFKa1VTNTFxcXJlak9IbFpPaVR4Y21TMUxSdDFKZlA5ckpoWEpDT0FheHhaWUxxNjEyMUJHNTJ3VEYvUw==
  POSTGRES_URL: cG9zdGdyZXNxbDovL2RiYWRtaW46V0VRR2NfMm1weVRYRXBDUGthNmUyMXJsRFh3cFA2UlJfaHcwZVdrTDl4c0A0LjE1Mi4yMDEuMTcxOjU0MzIvb2ZmY2FsbF9haQ==
  REDIS_URL: cmVkaXNzOi8vOnkzRHFaV3JlajhySEx6ejVwbWpSbmF1SUdrN25EWjR2c0F6Q2FHMWxFQTg9QG9mZmNhbGwtYWktY29tcGxpYW5jZS1yZWRpcy5yZWRpcy5jYWNoZS53aW5kb3dzLm5ldDo2MzgwLzA=
  SECRET_KEY: SzkrUjFKa1VTNTFxcXJlak9IbFpPaVR4Y21TMUxSdDFKZlA5ckpoWEpDT0FheHhaWUxxNjEyMUJHNTJ3VEYvUw==
kind: Secret
metadata:
  creationTimestamp: "2025-08-10T08:11:43Z"
  name: offcall-ai-secrets
  namespace: offcall-ai
  resourceVersion: "588251"
  uid: 2d1b2502-3ef1-4833-9c31-5d381d5150df
type: Opaque
