"""Add missing models and fix relationships

Revision ID: 14fb53bae0af
Revises: 098c58a50bec
Create Date: 2025-09-19 00:47:51.575865

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '14fb53bae0af'
down_revision: Union[str, Sequence[str], None] = '098c58a50bec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('deployments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('incident_id', sa.UUID(), nullable=False),
    sa.Column('created_by_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('deployment_type', sa.Enum('HOTFIX', 'ROLLBACK', 'ROUTINE', 'EMERGENCY', name='deploymenttype'), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'SUCCESS', 'FAILED', 'CANCELLED', name='deploymentstatus'), nullable=True),
    sa.Column('repository_url', sa.String(length=500), nullable=True),
    sa.Column('branch', sa.String(length=100), nullable=True),
    sa.Column('commit_hash', sa.String(length=40), nullable=True),
    sa.Column('deployment_script', sa.Text(), nullable=True),
    sa.Column('completed_steps', sa.Integer(), nullable=True),
    sa.Column('failed_steps', sa.Integer(), nullable=True),
    sa.Column('execution_environment', sa.String(length=100), nullable=True),
    sa.Column('container_id', sa.String(length=255), nullable=True),
    sa.Column('resource_limits', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('total_duration', sa.Integer(), nullable=True),
    sa.Column('estimated_duration', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('rollback_deployment_id', sa.UUID(), nullable=True),
    sa.Column('approval_required', sa.Boolean(), nullable=True),
    sa.Column('approved_by_id', sa.UUID(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['approved_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['rollback_deployment_id'], ['deployments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notifications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=True),
    sa.Column('incident_id', sa.UUID(), nullable=True),
    sa.Column('action_url', sa.String(length=500), nullable=True),
    sa.Column('extra_data', sa.JSON(), nullable=True),
    sa.Column('read', sa.Boolean(), nullable=True),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('deployment_steps',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('deployment_id', sa.UUID(), nullable=False),
    sa.Column('step_number', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('command', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'SUCCESS', 'FAILED', 'CANCELLED', name='deploymentstatus'), nullable=True),
    sa.Column('output', sa.Text(), nullable=True),
    sa.Column('error_output', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['deployment_id'], ['deployments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('alerts', 'external_id',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('alerts', 'source',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.alter_column('alerts', 'environment',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=50),
               existing_nullable=True)
    op.alter_column('alerts', 'started_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('alerts', 'raw_data',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True)
    op.create_index(op.f('ix_alerts_fingerprint'), 'alerts', ['fingerprint'], unique=False)
    op.alter_column('oauth_accounts', 'access_token',
               existing_type=sa.TEXT(),
               type_=sa.String(length=2000),
               existing_nullable=True)
    op.alter_column('oauth_accounts', 'refresh_token',
               existing_type=sa.TEXT(),
               type_=sa.String(length=2000),
               existing_nullable=True)
    op.alter_column('runbooks', 'created_by_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('runbooks', 'created_by_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('oauth_accounts', 'refresh_token',
               existing_type=sa.String(length=2000),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('oauth_accounts', 'access_token',
               existing_type=sa.String(length=2000),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_index(op.f('ix_alerts_fingerprint'), table_name='alerts')
    op.alter_column('alerts', 'raw_data',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False)
    op.alter_column('alerts', 'started_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.alter_column('alerts', 'environment',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
    op.alter_column('alerts', 'source',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
    op.alter_column('alerts', 'external_id',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.drop_table('deployment_steps')
    op.drop_table('notifications')
    op.drop_table('deployments')
    # ### end Alembic commands ###
