"""Add audit_log table and incident fields

Revision ID: 97839479fc0d
Revises: b5ff3c5d9b17
Create Date: 2025-09-11 18:59:28.417292

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '97839479fc0d'
down_revision: Union[str, Sequence[str], None] = 'b5ff3c5d9b17'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
